bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('account/', include('account.urls')),
    path('social-auth/',
         include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('', views.image_list, name='list'),
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',
         views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('ranking/', views.image_ranking, name='ranking'),
    path('delete/', views.image_delete, name='delete'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from cloudinary.models import CloudinaryField

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = CloudinaryField('image')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name='images_liked',
                                       blank=True)
    total_likes = models.PositiveIntegerField(db_index=True,
                                              default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from .models import Image
from urllib.request import Request, urlopen
from django.core.files.base import ContentFile
from django.utils.text import slugify

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = {'title', 'url', 'description'}
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url'].split('?')[0]
        # if compressed change compression url to full sized pic
        # if
        valid_extensions = ['jpg', 'jpeg']
        if "jpg" in str(url):
            extension = "jpg"
        else:
            extension = "jpeg"
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not '\
                                        'match valid image extensions.')
        return url

    def save(self, force_insert=False,
                   force_update=False,
                   commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        if "jpg" in str(image_url):
            extension = "jpg"
        else:
            extension = "jpeg"
        image_name = f'{name}.{extension}'

        #download image from the given URL
        req = Request(image_url, headers= {"User-Agent": "Mozilla/5.0"})
        response = urlopen(req)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from common.column import make_column
from common.decorators import ajax_required
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, \
                                    PageNotAnInteger
from actions.utils import create_action, delete_action
# from django.db.models import Count

import os
import redis
from django.conf import settings

# connect to redis
r = redis.from_url(os.getenv('REDIS_URL'))

@login_required
def image_create(request):
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_item = form.save(commit=False)

            # assign current user to the item
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Image added successfully')

            # redirect to new created item detail view
            return redirect(new_item.get_absolute_url())
    else:
        # build the form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)

    return render(request,
                  'images/image/create.html',
                  {'section': 'images',
                   'form': form})

@login_required
def image_detail(request, id, slug):
    print(request.session)
    image = get_object_or_404(Image, id=id, slug=slug)
    # increment total image views by 1
    total_views = r.incr(f'image:{image.id}:views')
    # increment image ranking by 1
    r.zincrby('image_ranking', 1, image.id)
    return render(request,
                  'images/image/detail.html',
                  {'section': 'images',
                   'image': image,
                   'total_views': total_views})

@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'error'})

@login_required
def image_list(request):
    images = Image.objects.order_by('-total_likes')
    # images = images.annotate(total_likes=Count('users_like')).order_by('-total_likes')
    paginator = Paginator(images, 9)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # If the page is not an integer deliver the first page
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # If the request is AJAX and the page is out of range
            # return an empty page
            return HttpResponse('')
        # If page is out of range deliver last page of results
        images = paginator.page(paginator.num_pages)

    cols = make_column(images)
    if request.is_ajax():
        return render(request,
                      'images/image/list_ajax.html',
                      {'section': 'images', 'images': images, 'cols': cols})
    return render(request,
                  'images/image/list.html',
                  {'section': 'images', 'images': images, 'cols': cols})

@login_required
def image_ranking(request):
    # get image ranking dictionary
    image_ranking = r.zrange('image_ranking', 0, -1,
                             desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    # get most viewed images
    most_viewed = list(Image.objects.filter(
                            id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request,
                  'images/image/ranking.html',
                  {'section': 'images',
                  'most_viewed': most_viewed})

@require_POST
@login_required
def image_delete(request):
    print("this view is running")
    image_id = request.POST['image_id']
    image = Image.objects.get(id=image_id)
    delete_action(image)
    image.delete()
    return JsonResponse({'delete': 'success'})

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Bookmark an image{% endblock %}

{% block content %}
  <h1>Bookmark an image</h1>
  <img src="{{ request.GET.url }}" class="image-preview">
  <form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!">
  </form>
{% endblock %}    

images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content  %}
  <h1>{{ image.title }}</h1>
  {% load thumbnail %}
  <div>
    {% if image.user == request.user %}
      <p>This image is your contribution to the collage!</p>
      <span class="btn-danger btn-sm close" id="image-delete">
        <a href="#">&times</a>
      </span>
    {% else %}
      <p>Contributer:
      <span class="image-user">
        <a href="{% url 'user_detail' image.user.username %}">
          <img src="{{ image.user.profile.photo.url }}" alt="">
        </a>
      </span></p>
    {% endif %}
    <a href="{{ image.image.url }}">
      <img src="{% thumbnail image.image 500x0 %}" class="image-detail">
    </a>
  </div>
  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
        <span class="count">
          {{ total_views }} view{{ total_views|pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks }}
    </div>
    <h3>Likes:</h3>
    <div class="image-likes">
      {% for user in users_like %}
        <div>
          <img src="{{ user.profile.photo.url }}" alt="">
          <p>{{ user.first_name }}</p>
        </div>
      {% empty %}
        Nobody likes this image yet.
      {% endfor %}
    </div>
  {% endwith %}
{% endblock %}

{% block domready %}
  $('a.like').click(function(e) {
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data) {
        if (data['status'] == 'ok') {
          var previous_action = $('a.like').data('action');

          {# alert("server says: "+ data['name']) #}
          //toggle data-action
          $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');

          //toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

          //update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
        }
      });
  });
  $('#image-delete').click(function() {
    if (confirm('Are you sure to DELETE this image?')) {
      $.post('{% url 'images:delete' %}',
      {
        image_id: {{ image.id }}
      },
      function(data) {
        if (data['delete'] == 'success') {
          window.location = '{% url "images:list" %}'
        }
      })
    }
  })
{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Image bookmarked{% endblock %}

{% block content %}
  <h1>Images bookmarked</h1>
  <div id="image-list">
    {% include "images/image/list_ajax.html" %}
  </div>
{% endblock %}
{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 400;
    if($(window).scrollTop() > margin && empty_page == false &&
    block_request == false) {
      block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
        if(data == '') {
          empty_page = true;
        }else{
          block_request = false;
          $('#image-list').append(data);
        }
      });
    }
  });
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}
  {% if not request.is_ajax %}
    <div class="row">
      {% for images in cols.values %}
        <div class="column column{{ forloop.counter }}">
          {% for image in images %}
            {% thumbnail image.image 300x0 as im %}
            <a href="{{ image.get_absolute_url }}">
              <img src="{{ image.get_absolute_url }}" alt="" width="300" height="0">
            </a>
            <div class="info">
              <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title|truncatewords:5 }}
              </a>
            </div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  {% else %}
  {% for images in cols.values %}
    <script type="text/javascript">
      $(".row .column{{ forloop.counter }}").append(`
        {% for image in images %}
          {% thumbnail image.image 300x0 as im %}
          <a href="{{ image.get_absolute_url }}">
            <img src="{{ image.image.url }}" alt="">
          </a>
          <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
              {{ image.title|truncatewords:5 }}
            </a>
          </div>
        {% endfor %}
      `)
    </script>
    {% endfor %}
  {% endif %}

images/templates/images/image/ranking.html
{% extends "base.html" %}

{% block title %}Images ranking{% endblock %}

{% block content %}
  <h1>Images ranking</h1>
  <ol>
    {% for image in most_viewed %}
      <li>
        <a href="{{ image.get_absolute_url }}">
          {{ image.title }}
        </a>
      </li>
    {% endfor %}
  </ol>
{% endblock %}